-- insert into card_types------------------------------------------------------------------------------
INSERT INTO CARD_TYPES (NAME) VALUES ('Credit');
INSERT INTO CARD_TYPES (NAME) VALUES ('Debit');

-- insert into music_genres------------------------------------------------------------------------------
INSERT INTO MUSIC_GENRES(NAME) VALUES('Hip Hop');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Classical');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Jazz');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Heavy Metal');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Pop');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Technical Death Metal');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Grunge');
INSERT INTO MUSIC_GENRES(NAME) VALUES('Electronic');

-- insert into music_artists------------------------------------------------------------------------------
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Eminem');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Drake');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Wolfgang Amadeus Mozart');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Pyotr Ilyich Tchaikovsky');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Louis Armstrong');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Billie Holiday');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Black Sabbath');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Iron Maiden');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Taylor Swift');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Michael Jackson');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Necrophagist');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Soundgarden');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Green River');
INSERT INTO MUSIC_ARTISTS(NAME) VALUES('Skrillex');

-- insert into music_albums------------------------------------------------------------------------------
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('The Slim Shady LP', 10.99, TO_DATE('1999-02-23', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Eminem'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Scorpion', 14.99, TO_DATE('2018-06-29', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Drake'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Mozart in the Morning', 10.99, TO_DATE('1992-09-15', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Wolfgang Amadeus Mozart'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Nutcracker Suite', 10.99, TO_DATE('1927-01-01', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Pyotr Ilyich Tchaikovsky'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Hello, Dolly!', 10.99, TO_DATE('1964-04-18', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Louis Armstrong'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Louis and the Angels', 12.99, TO_DATE('1957-02-01', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Louis Armstrong'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Lady in Satin', 10.99, TO_DATE('1958-06-01', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Billie Holiday'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Paranoid', 12.99, TO_DATE('1970-09-18', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Black Sabbath'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Master of Reality', 12.99, TO_DATE('1971-07-21', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Black Sabbath'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('The Number of the Beast', 12.99, TO_DATE('1982-03-22', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Iron Maiden'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('1989', 14.99, TO_DATE('2014-10-27', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Taylor Swift'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Thriller', 17.99, TO_DATE('1982-11-30', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Michael Jackson'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Epitaph', 10.99, TO_DATE('2004-09-03', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Necrophagist'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Badmotorfinger', 10.99, TO_DATE('1991-09-24', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Soundgarden'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Louder Than Love', 10.99, TO_DATE('1989-09-05', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Soundgarden'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Rehab Doll', 10.99, TO_DATE('1988-07-01', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Green River'));
INSERT INTO MUSIC_ALBUMS(NAME, PRICE, RELEASE_DATE, ARTIST_ID)
VALUES ('Recess', 11.99, TO_DATE('2014-03-18', 'YYYY-MM-DD'), (SELECT ARTIST_ID FROM MUSIC_ARTISTS WHERE NAME='Skrillex'));

-- insert into songs------------------------------------------------------------------------------
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('My Name Is', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Guilty Conscience', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('97 Bonnie &. Clyde', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Role Model', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('I''m Shady', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Survival', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Scorpion'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('God''s Plan', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Scorpion'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('8 Out of 10', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Scorpion'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Mob Ties', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Scorpion'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('In My Feelings', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Scorpion'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Hip Hop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Le nozze di Figaro', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Serenade in G', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Symphony No. 28', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Don Giovanni', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Piano Sonata No. 11', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('March', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Departure of the Guests', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Arabian Dance', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Pas de Deus', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Code - Apotheosis', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Classical'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Hello, Dolly!', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('It''s Been a Long, Long Time', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('A Lot of Livin'' to Do', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('A Kiss to Build a Dream On', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Hey, Look Me Over', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('When Did You Leave Heaven?', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louis and the Angels'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('You''re a Heavenly Thing', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louis and the Angels'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('I Married an Angel', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louis and the Angels'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Fools Rush In', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louis and the Angels'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('I''m a Fool to Want You', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('For Heaven''s Sake', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('You Don''t Know What Love Is', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('For All We Know', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('I''ll Be Around', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Jazz'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('War Pigs', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Paranoid'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Paranoid', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Paranoid'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Iron Man', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Paranoid'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Fairies Wear Boots', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Paranoid'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Hand of Doom', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Paranoid'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Sweet Leaf', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Master of Reality'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('After Forever', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Master of Reality'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Children of the Grave', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Master of Reality'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Solitude', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Master of Reality'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Orchid', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Master of Reality'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Invaders', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Number of the Beast'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('The Number of the Beast', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Number of the Beast'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Run to the Hills', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Number of the Beast'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Hallowed Be Thy Name', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Number of the Beast'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Heavy Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Welcome to New York', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='1989'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Blank Space', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='1989'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Style', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='1989'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Bad Blood', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='1989'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Wildest Dreams', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='1989'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Wanna Be Startin'' Somethin''', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Thriller'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Thriller', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Thriller'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Beat It', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Thriller'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Billie Jean', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Thriller'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Human Nature', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Thriller'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Pop'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Epitaph', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Epitaph'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Technical Death Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Ignominious and Pale', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Epitaph'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Technical Death Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('The Stillborn One', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Epitaph'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Technical Death Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Diminished to B', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Epitaph'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Technical Death Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Symbiotic in Theory', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Epitaph'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Technical Death Metal'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Jesus Christ Pose', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Rusty Cage', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Outshined', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Room a Thousand Years Wide', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Holy Water', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Ugly Truth', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louder Than Love'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Hands All Over', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louder Than Love'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Loud Love', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louder Than Love'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Uncovered', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louder Than Love'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Full On', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Louder Than Love'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Forever Means', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Rehab Doll'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Rehab Doll', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Rehab Doll'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Swallow My Pride', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Rehab Doll'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Together We''ll Never', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Rehab Doll'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Smilin'' and Dyin''', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Rehab Doll'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Take a Dive', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Rehab Doll'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Grunge'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('All Is Fair in Love and Brostep', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Recess'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Electronic'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Recess', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Recess'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Electronic'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Stranger', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Recess'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Electronic'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Ease My Mind', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Recess'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Electronic'));
INSERT INTO SONGS(NAME, ALBUM_ID, GENRE_ID)
VALUES ('Fire Away', (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Recess'), (SELECT GENRE_ID FROM MUSIC_GENRES WHERE NAME='Electronic'));

-- insert into transactions------------------------------------------------------------------------------
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='iulian999'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Badmotorfinger'), TO_DATE('2020-11-06','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='iulian999'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Number of the Beast'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='The Number of the Beast'), TO_DATE('2017-05-29','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='muzner81'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Thriller'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Thriller'), TO_DATE('2007-05-15','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='muzner81'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), TO_DATE('2010-10-11','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='geomurr88'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Mozart in the Morning'), TO_DATE('2009-01-29','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='geomurr88'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Scorpion'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Scorpion'), TO_DATE('2012-11-01','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='sarahh'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Paranoid'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Paranoid'), TO_DATE('2018-10-5','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='g_williams12'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Epitaph'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Epitaph'), TO_DATE('2005-08-01','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='g_williams12'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='The Slim Shady LP'), TO_DATE('2006-09-21','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='g_williams12'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Hello, Dolly!'), TO_DATE('2006-09-21','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='g_williams12'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Lady in Satin'), TO_DATE('2006-09-21','YYYY-MM-DD'));
INSERT INTO TRANSACTIONS(USER_ID, ALBUM_ID, AMOUNT, "date")
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME='g_williams12'), (SELECT ALBUM_ID FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'),
(SELECT PRICE FROM MUSIC_ALBUMS WHERE NAME='Nutcracker Suite'), TO_DATE('2006-09-21','YYYY-MM-DD'));